// Generated by Copilot
using System.Globalization;
using System.Text.Json.Serialization;
using CsvHelper.Configuration.Attributes;

namespace TogglTimesheet.Timesheet
{
    public class TimeEntry
    {
        private const string DateFormat = "yyyy-MM-dd";
        public string Project { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;

        [Name("Start date")]
        [JsonIgnore]
        public string RawStartDate { get; set; } = string.Empty;

        public DateTime StartDate => DateTime.TryParseExact(
            RawStartDate,
            DateFormat,
            CultureInfo.InvariantCulture,
            DateTimeStyles.None,
            out var parsedStartDate)
            ? parsedStartDate
            : DateTime.MinValue;

        [Name("Duration")]
        [JsonIgnore]
        public string RawDuration { get; set; } = string.Empty;

        public double Duration => TimeSpan.Parse(RawDuration).TotalHours;
    }

    public class ReportedTimeEntry
    {
        public string Task { get; set; } = string.Empty;
        public Dictionary<DateTime, double> DayTime { get; set; } = new();
    }
}
