// Generated by Copilot
using Microsoft.AspNetCore.Mvc;
using TogglTimesheet.Timesheet;

namespace TogglTimesheet.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TimesheetController : ControllerBase
    {
        private readonly ITimesheetGenerator _timesheetGenerator;
        private readonly ITimeDataLoader _timeDataLoader;

        public TimesheetController(ITimesheetGenerator timesheetGenerator, ITimeDataLoader timeDataLoader)
        {
            _timesheetGenerator = timesheetGenerator;
            _timeDataLoader = timeDataLoader;
        }

        [HttpPost("generate")]
        public IActionResult GenerateTimesheet([FromForm] IFormFile csvFile)
        {
            if (csvFile == null || csvFile.Length == 0)
            {
                return BadRequest("CSV file is required.");
            }

            using var stream = csvFile.OpenReadStream();
            var timesheetData = _timesheetGenerator.GenerateData(stream);
            return File(timesheetData, "application/octet-stream", "timesheet.csv");
        }

        [HttpGet("load-time")]
        public async Task<IActionResult> LoadTimeEntries(string apiToken, string workspaceId, DateTime startDate, DateTime endDate)
        {
            const string DateFormat = "yyyy-MM-dd";

            string startDateString = startDate.ToString(DateFormat);
            string endDateString = endDate.ToString(DateFormat);

            var timeData = await _timeDataLoader.FetchTimeDataAsync(apiToken, workspaceId, startDateString, endDateString);
            return Ok(timeData);
        }
    }
}
